#!/bin/bash
 
# Dependencies:
# imagemagick
# i3lock-color-git
# scrot
xset dpms force on 
cd ~/.config/i3lock-fancy-pixellated-user
 
IMAGE=/tmp/i3lock.png


 
# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
#BLURTYPE="0x5" # 7.52s
#BLURTYPE="0x2" # 4.39s
#BLURTYPE="5x3" # 3.80s
#BLURTYPE="2x8" # 2.90s
#BLURTYPE="2x3" # 2.92s
sleep 0.3
scrot $IMAGE

uinfo=$(getent passwd $USER)
IFS=':' read -a array <<< "$uinfo"

cp /var/lib/AccountsService/icons/$USER user.png
rm user_circ.png
rm user_1.png
convert user.png -resize 188x188 user_1.png
convert -size 188x188 xc:none -fill user_1.png -draw "circle 94,94 94,1" user_circ.png
convert $IMAGE -level 0%,100%,1.0 -scale 5% -scale 2000% -brightness-contrast -33x-25 /tmp/i3lock.png -font ./System\ San\ Francisco\ Display\ Thin.ttf -pointsize 26 -fill white -gravity center -annotate +0+200 'Enter your password to unlock' -font ./System\ San\ Francisco\ Display\ Bold.ttf -pointsize 36 -fill white -gravity center -annotate +0-200 "${array[4]}" - | composite -gravity center user_circ.png - $IMAGE
i3lock --textcolor=ffffff00 --insidecolor=ffffff1c --ringcolor=ffffff3e --linecolor=ffffff00 --keyhlcolor=00000080 --ringvercolor=00000000 --insidevercolor=0000001c --ringwrongcolor=00000055 --insidewrongcolor=0000001c  -i $IMAGE &
sleep 5 && xset dpms force off
rm $IMAGE
